spring:
    application:
        name: demo
    profiles:
        active: dev
        group:
            dev: dev, secret
            blue: blue, secret, prod
            green: green, secret, prod
    datasource:
        url:
        username:
        password:
        driver-class-name:

    decorator:
        datasource:
            p6spy:
            enable-logging: true

    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
        show-sql: false
        properties:
            hibernate:
    # rabbitMQ(Notification )
    rabbitmq:
      host: localhost
      port: 5672
      username: 
      password: 
      
    data:
        redis:
            host:
            port: 6379
            password:
        mongodb:
            uri:

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id:
                        client-secret:
                        redirect-uri:
                        authorization-grant-type: authorization_code
                        scope: # google API의 범위 값
                            - profile
                            - email

                    kakao:
                        client-id:
                        client-secret:
                        redirect-uri:
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        scope: # kakao 개인 정보 동의 항목 설정의 ID 값
                            - profile_nickname
                            - profile_image
                            - account_email
                        client-name: kakao

                    naver:
                        client-id:
                        client-secret:
                        redirect-uri:
                        authorization-grant-type: authorization_code
                        scope: name, email, profile_image
                        client-name: naver

                    # provider 설정
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id

                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
server:
    env: dev

---
spring:
    config:
        activate:
            on-profile: dev
server:
    port: 8080
custom:
    baseUrl: http://localhost:8080

serverName: dev_server

---
spring:
    config:
        activate:
            on-profile: blue

server:
    port: 8080

serverName: blue_server

---
spring:
    config:
        activate:
            on-profile: green
server:
    port: 8081

serverName: green_server

---
spring:
    config:
        activate:
            on-profile: prod
    decorator:
        datasource:
            p6spy:
                enable-logging: false
custom:
    baseUrl: https://api.ddokdoghotdog.shop

---

